#!/bin/bash
#SBATCH --job-name=RTE_fixH1e-6_1027	# Job name (testBowtie2)
#SBATCH --partition=gpu_p		# Partition name (batch, highmem_p, or gpu_p)
#SBATCH --ntasks=1			# 1 task (process) for below commands
#SBATCH --cpus-per-task=2	 	# CPU core count per task, by default 1 CPU core per task
#SBATCH --mem=120G			# Memory per node (4GB); by default using M as unit
#SBATCH --gres=gpu:L4:1
#SBATCH --time=15:00:00             	# Time limit hrs:min:sec or days-hours:minutes:seconds
#SBATCH --output=jobs/%x_%j_1.out		# Standard output log, e.g., testBowtie2_12345.out
#SBATCH --mail-user=jichao.yu@uga.edu    # Where to send mail
#SBATCH --mail-type=ALL          	# Mail events (BEGIN, END, FAIL, ALL)

ml Miniconda3/23.5.2-0
ml CUDA/12.1.1
ml jq

source ~/.bashrc
conda activate ciao
cd /home/jy03364/MeZO/medium_models

# original without c
TASK=RTE K=16 SEED=16 BS=8 LR=1e-6 EPS=1e-6 MODEL=roberta-large USE_H=False USE_LH=False USE_C=False bash mezo.sh